CREATE TABLE APP_USER(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(50),
);

CREATE TABLE PET(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    breed VARCHAR(50) NOT NULL,
    birthdate DATE NOT NULL,
    owner_id BIGINT NOT NULL
    FOREIGN KEY(owner_id) REFERENCES APP_USER(id),
);

CREATE TABLE VACCINE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    dose DECIMAL(5,2) NOT NULL,
    vaccine_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    pet_id BIGINT NOT NULL
    FOREIGN KEY(pet_id) REFERENCES PET(id)
);